export PATH=~/.npm-global/bin:$PATH
export EDITOR=vim

# Naviagation
alias cdfe="cd ~/vv/vvh-frontend-pwa"
alias cd8b="cd ~/vv/8base-backend"
alias cdvr="cd ~/vv/vr_application"
alias cdaws="cd ~/vv/aws-backend"
alias cdcon="cd ~/.config/"

# Git
alias gcm="git checkout master"
alias gcs="git checkout release/staging"
alias gcp="git checkout release/production"
alias gmm="git merge master"
alias gcne="git commit --amend --no-edit"

# 8base
alias 8be="8base environment"
alias 8bd="8base deploy"
alias 8bm="8base migration"
alias 8bi="8base invoke"
alias 8bil="8base invoke-local"
alias 8bb="8base backup"

# AWS SAM
alias sb="sam build"
alias sbr="sam build ReportGenerator"
alias sbd="sam build DicomGenerator"
alias sbt="sam build ReportGeneratorTrigger"
alias si="sam local invoke"
alias sir="sam local invoke ReportGenerator -e events/reportEvent_local.json"
alias sid="sam local invoke DicomGenerator -e events/reportEvent_local.json"
alias sd="sam deploy"

# AWS
alias awsi="aws lambda invoke --function-name"
alias awsir="aws lambda invoke --function-name ReportGenerator --payload fileb://events/reportEvent.json outfile.txt"
alias awsid="aws lambda invoke --function-name DicomGenerator --payload fileb://events/reportEvent.json outfile.txt"

# Interpreters
alias p="python"
alias n="node"

# Starship
eval "$(starship init zsh)"

# Fuzzy Finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
