# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH=~/.npm-global/bin:$PATH
export EDITOR=vim

# Naviagation
alias cdfe="cd ~/vv/vvh-frontend-pwa"
alias cd8b="cd ~/vv/8base-backend"
alias cdvr="cd ~/vv/vr_application"
alias cdaws="cd ~/vv/aws-backend"
alias cddot="cd ~/.config/dotfiles"

# Git
alias gcm="git checkout master"
alias gcs="git checkout release/staging"
alias gcp="git checkout release/production"
alias gmm="git merge master"
alias grm="git rebase -i master"
alias grc="git rebase --continue"
alias gra="git rebase --abort"
alias grs="git rebase --skip"
alias gcne="git commit --amend --no-edit"


# 8base
alias 8be="8base environment"
alias 8bd="8base deploy"
alias 8bm="8base migration"
alias 8bi="8base invoke"
alias 8bil="8base invoke-local"
alias 8bb="8base backup"

# AWS SAM
alias sb="sam build"
alias sbr="sam build ReportGenerator"
alias sbd="sam build DicomGenerator"
alias sbt="sam build ReportGeneratorTrigger"
alias si="sam local invoke"
alias sir="sam local invoke ReportGenerator -e events/reportEvent_local.json"
alias sid="sam local invoke DicomGenerator -e events/reportEvent_local.json"
alias sd="sam deploy"

# AWS
alias awsi="aws lambda invoke --function-name"
alias awsir="aws lambda invoke --function-name ReportGenerator --payload fileb://events/reportEvent.json outfile.txt"
alias awsid="aws lambda invoke --function-name DicomGenerator --payload fileb://events/reportEvent.json outfile.txt"

# Tmux
alias ta="tmux a -t 0"
alias ta1="tmux a -t 1"
alias ta2="tmux a -t 2"
alias ta3="tmux a -t 3"
alias ta4="tmux a -t 4"
alias ta5="tmux a -t 5"

# Tmux - VV Specific
alias taf="tmux a -t fe"
alias ta8="tmux a -t 8b"
alias taa="tmux a -t aws"

# Interpreters
alias p="python"
alias n="node"
alias vim="/usr/local/bin/vim" # brew version with python3

# Shortcuts
alias c="clear"

# Fuzzy Finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.config/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
