import = ["/Users/justin/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Regular"

[scrolling]
history = 100000

[window]
title = "Virutal Vision Software Development Kit (VVSDK)"
option_as_alt = "Both"
opacity = 0.95
